//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.14 at 08:56:38 PM CEST 
//


package com.rvh.openoffice.model.officepackage.contentTypes;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for CT_Types complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_Types">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://schemas.openxmlformats.org/package/2006/content-types}Default"/>
 *         &lt;element ref="{http://schemas.openxmlformats.org/package/2006/content-types}Override"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_Types", propOrder = {
    "defaultOrOverride"
})
@XmlRootElement(name = "Types")
public class CTTypes {

    @XmlElements({
        @XmlElement(name = "Default", type = com.rvh.openoffice.model.officepackage.contentTypes.CTDefault.class),
        @XmlElement(name = "Override", type = com.rvh.openoffice.model.officepackage.contentTypes.CTOverride.class)
    })
    protected List<Object> defaultOrOverride;

    /**
     * Gets the value of the defaultOrOverride property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the defaultOrOverride property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDefaultOrOverride().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTDefault }
     * {@link CTOverride }
     * 
     * 
     */
    public List<Object> getDefaultOrOverride() {
        if (defaultOrOverride == null) {
            defaultOrOverride = new ArrayList<Object>();
        }
        return this.defaultOrOverride;
    }

}
